_wandb:
    value:
        cli_version: 0.26.1
        e:
            asvho64ph8ep7uy4vh4w3l01mard9cwp:
                args:
                    - --model
                    - improved_gat
                    - --config
                    - configs/benchmark_full.yml
                    - --session
                    - gat_full
                    - --trial
                    - "38"
                    - --random
                codePath: src\scripts\hp_search.py
                codePathLocal: src\scripts\hp_search.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023301120000"
                        used: "420058886144"
                email: miguelmcabralpinto@gmail.com
                executable: C:\Users\Usuario\git\Misinformation-GNN\env\Scripts\python.exe
                git:
                    commit: f1e434219ffe2ff84841f3ef86391d11d6e35737
                    remote: https://github.com/NunoMBatista/Misinformation-GNN.git
                gpu: NVIDIA GeForce RTX 5060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3840
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060
                      uuid: GPU-4983f234-9190-3b0a-164e-9bc92783939f
                host: DESKTOP-J8HGHTU
                memory:
                    total: "33938018304"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Usuario\git\Misinformation-GNN\src\scripts\hp_search.py
                python: CPython 3.12.9
                root: C:\Users\Usuario\git\Misinformation-GNN
                startedAt: "2026-05-12T12:02:28.591832Z"
                writerId: asvho64ph8ep7uy4vh4w3l01mard9cwp
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.9
            "5": 0.26.1
            "6": 5.8.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.26.1
            "13": windows-amd64
dropout:
    value: 0.2881
edge_direction:
    value: bidirectional
epochs:
    value: 150
focal_gamma:
    value: 2.0972
heads:
    value: 1
hidden_dims:
    value:
        - 64
        - 32
input_dim:
    value: 392
learning_rate:
    value: 0.003496
model:
    value: improved_gat
trial:
    value: 38
use_focal_loss:
    value: true
weight_decay:
    value: 1.7e-05
