_wandb:
    value:
        cli_version: 0.26.1
        e:
            k1zfp9gqde91u8f8e4x7h7q9x4jjyqds:
                args:
                    - --model
                    - mlp
                    - --config
                    - configs/benchmark_full.yml
                    - --session
                    - mlp50
                    - --trial
                    - "35"
                    - --hparams
                    - '{"hidden_dims":[128,64,32],"dropout":0.42,"learning_rate":0.000075,"weight_decay":0.00003,"focal_gamma":4.0}'
                codePath: src\scripts\hp_search.py
                codePathLocal: src\scripts\hp_search.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023301120000"
                        used: "419996450816"
                email: miguelmcabralpinto@gmail.com
                executable: C:\Users\Usuario\git\Misinformation-GNN\env\Scripts\python.exe
                git:
                    commit: f1e434219ffe2ff84841f3ef86391d11d6e35737
                    remote: https://github.com/NunoMBatista/Misinformation-GNN.git
                gpu: NVIDIA GeForce RTX 5060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3840
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060
                      uuid: GPU-4983f234-9190-3b0a-164e-9bc92783939f
                host: DESKTOP-J8HGHTU
                memory:
                    total: "33938018304"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Usuario\git\Misinformation-GNN\src\scripts\hp_search.py
                python: CPython 3.12.9
                root: C:\Users\Usuario\git\Misinformation-GNN
                startedAt: "2026-05-11T18:36:13.416833Z"
                writerId: k1zfp9gqde91u8f8e4x7h7q9x4jjyqds
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.9
            "5": 0.26.1
            "6": 5.8.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.26.1
            "13": windows-amd64
dropout:
    value: 0.42
epochs:
    value: 100
focal_gamma:
    value: 4
hidden_dims:
    value:
        - 128
        - 64
        - 32
input_dim:
    value: 392
learning_rate:
    value: 7.5e-05
model:
    value: mlp
trial:
    value: 35
use_focal_loss:
    value: true
weight_decay:
    value: 3e-05
