_wandb:
    value:
        cli_version: 0.26.1
        e:
            k9ykncwz7iz40ftfjexg1tjtp63kna5f:
                args:
                    - --model
                    - improved_gnn
                    - --config
                    - configs/benchmark_structural_only.yml
                    - --session
                    - gnn_struct
                    - --trial
                    - "54"
                    - --random
                codePath: src\scripts\hp_search.py
                codePathLocal: src\scripts\hp_search.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023301120000"
                        used: "420303822848"
                email: miguelmcabralpinto@gmail.com
                executable: C:\Users\Usuario\git\Misinformation-GNN\env\Scripts\python.exe
                git:
                    commit: f1e434219ffe2ff84841f3ef86391d11d6e35737
                    remote: https://github.com/NunoMBatista/Misinformation-GNN.git
                gpu: NVIDIA GeForce RTX 5060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3840
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060
                      uuid: GPU-4983f234-9190-3b0a-164e-9bc92783939f
                host: DESKTOP-J8HGHTU
                memory:
                    total: "33938018304"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Usuario\git\Misinformation-GNN\src\scripts\hp_search.py
                python: CPython 3.12.9
                root: C:\Users\Usuario\git\Misinformation-GNN
                startedAt: "2026-05-12T17:42:07.932694Z"
                writerId: k9ykncwz7iz40ftfjexg1tjtp63kna5f
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.9
            "5": 0.26.1
            "6": 5.8.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.26.1
            "13": windows-amd64
dropout:
    value: 0.4291
edge_direction:
    value: original
epochs:
    value: 150
focal_gamma:
    value: 2.9862
hidden_dims:
    value:
        - 32
        - 16
        - 8
input_dim:
    value: 6
learning_rate:
    value: 0.000315
model:
    value: improved_gnn
trial:
    value: 54
use_focal_loss:
    value: true
weight_decay:
    value: 2.2e-05
